//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LukeDucaSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArticleState
    {
        public tbl_ArticleState()
        {
            this.tbl_Article = new HashSet<tbl_Article>();
            this.tbl_Workflows = new HashSet<tbl_Workflows>();
        }
    
        public int Article_State_Id { get; set; }

        [Display(Name = "Article State")]
        public string Type { get; set; }
    
        public virtual ICollection<tbl_Article> tbl_Article { get; set; }
        public virtual ICollection<tbl_Workflows> tbl_Workflows { get; set; }
    }
}
