//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeDucaSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Workflows
    {
        public int Workflow_Id { get; set; }
        public int User_Id { get; set; }
        public int State_Id { get; set; }
    
        public virtual tbl_ArticleState tbl_ArticleState { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
