//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeDucaSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArticleState
    {
        public tbl_ArticleState()
        {
            this.tbl_Article = new HashSet<tbl_Article>();
        }
    
        public int Article_State_Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tbl_Article> tbl_Article { get; set; }
    }
}
