//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LukeDucaSEAssignment2Sit1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public tbl_Users()
        {
            this.tbl_Article = new HashSet<tbl_Article>();
            this.tbl_Workflows = new HashSet<tbl_Workflows>();
        }
    
        public int User_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Role_Id { get; set; }
    
        public virtual ICollection<tbl_Article> tbl_Article { get; set; }
        public virtual tbl_Roles tbl_Roles { get; set; }
        public virtual ICollection<tbl_Workflows> tbl_Workflows { get; set; }
    }
}
